cluster:
  peers:
    - 192.168.1.1:8080
    - 192.168.1.2:8080
    - 192.168.1.3:8080
  self: 0
standalone:
  addr: "127.0.0.1:9736"
engine:
  dirPath: "/tmp/kuloy-test"
  dataFileSize: 268435456
  indexType: "hashmap"
  syncWrites: false
  mergeInterval: 28800